version: '3'

services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: renatohvo/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: renatohvo/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge
